-- Q1. What is the total revenue generated by each product category?
SELECT category AS Category,
	ROUND(SUM(totalamount),2) AS Total_Revenue
FROM customer
GROUP BY category;

-- Q2. Which are the top 10 highest revenue-generating products?
SELECT productname AS Products,
	ROUND(SUM(totalamount),2) AS Total_Revenue
FROM customer
GROUP BY productname
ORDER BY Total_Revenue DESC
LIMIT 10;

-- Q3. Who are the top 10 customers based on total spending?
SELECT customername AS Customer_Name,
	ROUND(SUM(totalamount),2) AS Total_Spending
FROM customer
GROUP BY customerid,customername
ORDER BY Total_Spending DESC
LIMIT 10;

-- Q4. What is the monthly trend of total revenue over time?
SELECT
    DATE_FORMAT(orderdate, '%b-%Y') AS Month,
    ROUND(SUM(totalamount),2) AS Total_Revenue
FROM customer
GROUP BY DATE_FORMAT(orderdate, '%b-%Y'),
         YEAR(orderdate),
         MONTH(orderdate)
ORDER BY YEAR(orderdate), MONTH(orderdate);

-- Q5. Which payment method generates the highest revenue?
SELECT paymentmethod AS Payment_Method,
	ROUND(SUM(totalamount),2) AS Total_Revenue
FROM customer
GROUP BY paymentmethod
ORDER BY Total_Revenue DESC
LIMIT 1;

-- Q6. Which cities contribute the highest total revenue?
SELECT city AS City,
	ROUND(SUM(totalamount),2) AS Total_Revenue
FROM customer
GROUP BY city
ORDER BY Total_Revenue DESC;

-- Q7. What is the cancellation rate (OrderStatus = 'Cancelled') overall and by category?

-- Overall
SELECT
    COUNT(*) AS Total_Orders,
    SUM(orderstatus = 'Cancelled') AS Cancelled_Orders,
    ROUND((SUM(orderstatus = 'Cancelled') / COUNT(*)) * 100, 2) AS Cancellation_Rate
FROM customer;

-- By Category
SELECT
    COUNT(*) AS Total_Orders,
    SUM(orderstatus = 'Cancelled') AS Cancelled_Orders,
    ROUND((SUM(orderstatus = 'Cancelled') / COUNT(*)) * 100, 2) AS Cancellation_Rate
FROM customer;

-- Q8. Which brands generate the highest total revenue?
SELECT brand,
	ROUND(SUM(totalamount),2) AS Total_Revenue
FROM customer
GROUP BY brand
ORDER BY Total_Revenue DESC;

-- Q9. What is the average order value across different categories?
SELECT category AS Category,
	ROUND(AVG(totalamount),2) AS Avg_Order_Value
FROM customer
GROUP BY category
ORDER BY Avg_Order_Value DESC;

-- Q10. Which products have the highest total quantity sold?
SELECT productname AS Product,
	SUM(quantity) AS Quantity
FROM customer
GROUP BY productname
ORDER BY Quantity DESC;